{
  "formatVersion": "1.1",
  "component": {
    "group": "com.shepeliev",
    "module": "webrtc-kmp",
    "version": "0.125.11-jvm1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "webrtc-kmp-metadata-0.125.11-jvm1.jar",
          "url": "webrtc-kmp-0.125.11-jvm1.jar",
          "size": 48066,
          "sha512": "e003c036674b3425f555ec485bab849e56b1f3a87de223f69f65c9b04e2f7a7fa4f4a959ba6b9ae48399d554b9cbcc3c5f7f0d9d2037191f15ff0cbe4b943305",
          "sha256": "20956da56b044905e1b522136c808772641c7e270deda005d76dd3242ea28412",
          "sha1": "1a5f2a033ba51352642d161b0397307751dd8a60",
          "md5": "ebcd1292371cf9925e27043d383522c8"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "webrtc-kmp-kotlin-0.125.11-jvm1-sources.jar",
          "url": "webrtc-kmp-0.125.11-jvm1-sources.jar",
          "size": 62997,
          "sha512": "f6718a03c1175fb5033864537097aeb8bad4d98bb20659ce1e64554a195c870edae010c861c54f75332e0733b57ef66b38a83d25e877807491f4b83db05a296b",
          "sha256": "1dcb9228c2f5b9910030ac1c7ac83929a4bf4e9deeacc6cf501352a395ba8f78",
          "sha1": "05304a3fec2fffb9bdf10aae73ad8741cb8adb21",
          "md5": "ca1f5965df4196f4a2dc720cadef1020"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../webrtc-kmp-android/0.125.11-jvm1/webrtc-kmp-android-0.125.11-jvm1.module",
        "group": "com.shepeliev",
        "module": "webrtc-kmp-android",
        "version": "0.125.11-jvm1"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../webrtc-kmp-android/0.125.11-jvm1/webrtc-kmp-android-0.125.11-jvm1.module",
        "group": "com.shepeliev",
        "module": "webrtc-kmp-android",
        "version": "0.125.11-jvm1"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../webrtc-kmp-android/0.125.11-jvm1/webrtc-kmp-android-0.125.11-jvm1.module",
        "group": "com.shepeliev",
        "module": "webrtc-kmp-android",
        "version": "0.125.11-jvm1"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../webrtc-kmp-iosarm64/0.125.11-jvm1/webrtc-kmp-iosarm64-0.125.11-jvm1.module",
        "group": "com.shepeliev",
        "module": "webrtc-kmp-iosarm64",
        "version": "0.125.11-jvm1"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../webrtc-kmp-iosarm64/0.125.11-jvm1/webrtc-kmp-iosarm64-0.125.11-jvm1.module",
        "group": "com.shepeliev",
        "module": "webrtc-kmp-iosarm64",
        "version": "0.125.11-jvm1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../webrtc-kmp-iosarm64/0.125.11-jvm1/webrtc-kmp-iosarm64-0.125.11-jvm1.module",
        "group": "com.shepeliev",
        "module": "webrtc-kmp-iosarm64",
        "version": "0.125.11-jvm1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../webrtc-kmp-iossimulatorarm64/0.125.11-jvm1/webrtc-kmp-iossimulatorarm64-0.125.11-jvm1.module",
        "group": "com.shepeliev",
        "module": "webrtc-kmp-iossimulatorarm64",
        "version": "0.125.11-jvm1"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../webrtc-kmp-iossimulatorarm64/0.125.11-jvm1/webrtc-kmp-iossimulatorarm64-0.125.11-jvm1.module",
        "group": "com.shepeliev",
        "module": "webrtc-kmp-iossimulatorarm64",
        "version": "0.125.11-jvm1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../webrtc-kmp-iossimulatorarm64/0.125.11-jvm1/webrtc-kmp-iossimulatorarm64-0.125.11-jvm1.module",
        "group": "com.shepeliev",
        "module": "webrtc-kmp-iossimulatorarm64",
        "version": "0.125.11-jvm1"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../webrtc-kmp-iosx64/0.125.11-jvm1/webrtc-kmp-iosx64-0.125.11-jvm1.module",
        "group": "com.shepeliev",
        "module": "webrtc-kmp-iosx64",
        "version": "0.125.11-jvm1"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../webrtc-kmp-iosx64/0.125.11-jvm1/webrtc-kmp-iosx64-0.125.11-jvm1.module",
        "group": "com.shepeliev",
        "module": "webrtc-kmp-iosx64",
        "version": "0.125.11-jvm1"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../webrtc-kmp-iosx64/0.125.11-jvm1/webrtc-kmp-iosx64-0.125.11-jvm1.module",
        "group": "com.shepeliev",
        "module": "webrtc-kmp-iosx64",
        "version": "0.125.11-jvm1"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../webrtc-kmp-js/0.125.11-jvm1/webrtc-kmp-js-0.125.11-jvm1.module",
        "group": "com.shepeliev",
        "module": "webrtc-kmp-js",
        "version": "0.125.11-jvm1"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../webrtc-kmp-js/0.125.11-jvm1/webrtc-kmp-js-0.125.11-jvm1.module",
        "group": "com.shepeliev",
        "module": "webrtc-kmp-js",
        "version": "0.125.11-jvm1"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../webrtc-kmp-js/0.125.11-jvm1/webrtc-kmp-js-0.125.11-jvm1.module",
        "group": "com.shepeliev",
        "module": "webrtc-kmp-js",
        "version": "0.125.11-jvm1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../webrtc-kmp-jvm/0.125.11-jvm1/webrtc-kmp-jvm-0.125.11-jvm1.module",
        "group": "com.shepeliev",
        "module": "webrtc-kmp-jvm",
        "version": "0.125.11-jvm1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../webrtc-kmp-jvm/0.125.11-jvm1/webrtc-kmp-jvm-0.125.11-jvm1.module",
        "group": "com.shepeliev",
        "module": "webrtc-kmp-jvm",
        "version": "0.125.11-jvm1"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../webrtc-kmp-jvm/0.125.11-jvm1/webrtc-kmp-jvm-0.125.11-jvm1.module",
        "group": "com.shepeliev",
        "module": "webrtc-kmp-jvm",
        "version": "0.125.11-jvm1"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../webrtc-kmp-wasm-js/0.125.11-jvm1/webrtc-kmp-wasm-js-0.125.11-jvm1.module",
        "group": "com.shepeliev",
        "module": "webrtc-kmp-wasm-js",
        "version": "0.125.11-jvm1"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../webrtc-kmp-wasm-js/0.125.11-jvm1/webrtc-kmp-wasm-js-0.125.11-jvm1.module",
        "group": "com.shepeliev",
        "module": "webrtc-kmp-wasm-js",
        "version": "0.125.11-jvm1"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../webrtc-kmp-wasm-js/0.125.11-jvm1/webrtc-kmp-wasm-js-0.125.11-jvm1.module",
        "group": "com.shepeliev",
        "module": "webrtc-kmp-wasm-js",
        "version": "0.125.11-jvm1"
      }
    }
  ]
}
