{
  "formatVersion": "1.1",
  "component": {
    "url": "../../webrtc-kmp/0.125.11-jvm1/webrtc-kmp-0.125.11-jvm1.module",
    "group": "com.shepeliev",
    "module": "webrtc-kmp",
    "version": "0.125.11-jvm1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "webrtc-kmp-js-0.125.11-jvm1.klib",
          "url": "webrtc-kmp-js-0.125.11-jvm1.klib",
          "size": 204027,
          "sha512": "09acedfc29de1fd0abe4abb9176bffdaf7ab271a31501b8790410762accb1882b757bf98ddf6366cca7f5f70ead5c113b411335b3f3657748905990870e7b061",
          "sha256": "b525e4e0c05e689e306585f034f25a70dac3584c16cf5344f52a916998a529d1",
          "sha1": "2c70cd15a35df3d1cc0928724d3223c1b6404368",
          "md5": "07877c7831a76154cfa3b8cabd69145d"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "webrtc-kmp-js-0.125.11-jvm1.klib",
          "url": "webrtc-kmp-js-0.125.11-jvm1.klib",
          "size": 204027,
          "sha512": "09acedfc29de1fd0abe4abb9176bffdaf7ab271a31501b8790410762accb1882b757bf98ddf6366cca7f5f70ead5c113b411335b3f3657748905990870e7b061",
          "sha256": "b525e4e0c05e689e306585f034f25a70dac3584c16cf5344f52a916998a529d1",
          "sha1": "2c70cd15a35df3d1cc0928724d3223c1b6404368",
          "md5": "07877c7831a76154cfa3b8cabd69145d"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "webrtc-kmp-js-0.125.11-jvm1-sources.jar",
          "url": "webrtc-kmp-js-0.125.11-jvm1-sources.jar",
          "size": 49272,
          "sha512": "8a775dd8c32d459aef628a19bd0da4997d6541016472f7b5cb872f536d4689fa55dc5206c8c4d0e33a0ae7016ddb2ba93b69bbdfe652605142defe7b1239c10c",
          "sha256": "19b1b50b7179f0ac7779cb9582874c7b77b364426122ada26f995fdf32d80b19",
          "sha1": "dc35a5501e6d0ff93feb84a7c7a5cab3604582b6",
          "md5": "9da771ada33b49ee08dbf54cdc3e2d34"
        }
      ]
    }
  ]
}
